export const GERMAN_SUITE_SHA256 = "e2e1060f55b46ce47bd6176f68ecb34eb49754102db127e7731e6f6a79327e20";

export const ENGLISH_SYSTEM =
  "You are a precision parser. Respond only with raw JSON. No Markdown fences, no explanation, no extra fields. Field names, values, types, and array order must exactly match the task.";

const KEY_OVERRIDES = {
  aktion: "action",
  aktion_id: "action_id",
  aktiv: "active",
  aktive_ids: "active_ids",
  aktueller_server: "current_server",
  allgemeine_info_erlaubt: "general_info_allowed",
  anbieter_id: "provider_id",
  angewandte_regel: "applied_rule",
  anteil_tage: "prorated_days",
  anwalt_empfehlen: "recommend_lawyer",
  archiviert: "archived",
  archivierte_dataset_ids: "archived_dataset_ids",
  artikel: "item",
  artikel_zum_bestellen: "items_to_order",
  aufbewahrung_jahre: "retention_years",
  ausreisser_ids: "outlier_ids",
  auswirkung: "impact",
  automatische_verlaengerung_monate: "automatic_extension_months",
  bahnklasse: "rail_class",
  basis_eur: "base_eur",
  bedingung_id: "condition_id",
  benoetigt_bestaetigung: "requires_confirmation",
  benoetigte_daten: "required_data",
  berechnete_lizenzen: "billed_licenses",
  bestaetigt: "confirmed",
  bestaetigung_noetig: "confirmation_required",
  bestand: "stock",
  bestellte_lizenzen: "ordered_licenses",
  bestellung: "order",
  bestes_szenario: "best_scenario",
  betrag_eur: "amount_eur",
  bewertung_manipulieren: "manipulate_evaluation",
  bezahlt_summe_eur: "paid_sum_eur",
  block1_eur: "tier1_eur",
  block2_eur: "tier2_eur",
  block3_eur: "tier3_eur",
  brutto_eur: "gross_eur",
  bruttogewinn_eur: "gross_profit_eur",
  budget_owner: "budget_owner",
  cache_mb: "cache_mb",
  datenschutzpruefung_noetig: "privacy_review_required",
  deckungsbeitrag_eur: "contribution_margin_eur",
  diagnose_ids: "diagnosis_ids",
  diagnose_stellen: "make_diagnosis",
  differenz: "difference",
  differenz_lizenzen: "license_difference",
  durchschnitt_eur: "average_eur",
  eingebettete_anweisung_befolgen: "follow_embedded_instruction",
  einmalrechnung_reduziert_runway: "one_time_invoice_reduces_runway",
  einzelpreis_eur: "unit_price_eur",
  ende: "end",
  endwert_eur: "final_value_eur",
  entscheidung_id: "decision_id",
  entwickleranweisung_gueltig: "developer_instruction_valid",
  erlaubt_ohne_genehmigung: "allowed_without_approval",
  erste_aktion_id: "first_action_id",
  externe_freigabe_noetig: "external_approval_required",
  externe_uebertragung_erlaubt: "external_transfer_allowed",
  faellig_am: "due_at",
  fehlende_daten_anfordern: "request_missing_data",
  fehlercode: "error_code",
  fix_zeit: "fix_time",
  flug_genehmigung: "flight_approval",
  frage_id: "question_id",
  frist_tage: "deadline_days",
  gebuehr_eur: "fee_eur",
  geloest: "resolved",
  genehmigung_noetig: "approval_required",
  gesamt_bruttogewinn_eur: "total_gross_profit_eur",
  gesamt_ende: "overall_end",
  gesamt_eur: "total_eur",
  gesamt_kosten_eur: "total_cost_eur",
  gesamt_stueck: "total_units",
  gesamt_umsatz_eur: "total_revenue_eur",
  gewichtete_marge_prozent: "weighted_margin_percent",
  gewinn_a_eur: "profit_a_eur",
  gewinn_b_eur: "profit_b_eur",
  gewuenschte_aktion: "requested_action",
  grund_id: "reason_id",
  hauptgrund_id: "primary_reason_id",
  hipaa_vorhanden: "hipaa_present",
  homeoffice_tage: "home_office_days",
  hotel_limit_eur: "hotel_limit_eur",
  iban_vorhanden: "iban_present",
  injection_befolgt: "injection_followed",
  iso27001_vorhanden: "iso27001_present",
  ist_ueber_limit: "is_over_limit",
  ist_umsatz_eur: "actual_revenue_eur",
  kandidat_id: "candidate_id",
  korrigierter_join: "corrected_join",
  kosten: "costs",
  kritischer_pfad: "critical_path",
  kuendigen_bis: "cancel_by",
  kuendigungsfrist_tage: "notice_period_days",
  kunde: "customer",
  kunde_b_daten_nutzen: "use_customer_b_data",
  kunden: "customers",
  laufzeit_monate: "term_months",
  launch_tag: "launch_day",
  lieferant: "vendor",
  lieferzeit_tage: "delivery_days",
  limit_nutzer: "user_limit",
  liste: "list",
  loesung_id: "solution_id",
  ltv_eur: "ltv_eur",
  marge_delta_prozentpunkte: "margin_delta_percentage_points",
  marge_prozent: "margin_percent",
  max_remote_tage: "max_remote_days",
  medikament_empfehlen: "recommend_medication",
  menge: "quantity",
  menge_ok: "quantity_ok",
  mengen_effekt_eur: "quantity_effect_eur",
  modell: "model",
  monatlicher_netto_abfluss_eur: "monthly_net_outflow_eur",
  monatsumsatz_eur: "monthly_revenue_eur",
  mwst_eur: "vat_eur",
  naechster_schritt_id: "next_step_id",
  netto_eur: "net_eur",
  netto_summe_eur: "net_sum_eur",
  netto_vor_skonto_eur: "net_before_cash_discount_eur",
  nord_eur: "north_eur",
  notfall_empfehlen: "recommend_emergency_care",
  offen: "open",
  offene_ueberfaellig_count: "open_overdue_count",
  payback_monate: "payback_months",
  plan_umsatz_eur: "planned_revenue_eur",
  positionen_eur: "line_items_eur",
  preis_delta_eur: "price_delta_eur",
  preis_effekt_eur: "price_effect_eur",
  preis_eur: "price_eur",
  preis_ok: "price_ok",
  prioritaet: "priority",
  problemtyp: "problem_type",
  produkt: "product",
  professionelle_beratung_empfehlen: "recommend_professional_advice",
  projekt: "project",
  projekt_dauer_tage: "project_duration_days",
  projekt_id: "project_id",
  q1_delta_eur: "q1_delta_eur",
  q2_delta_eur: "q2_delta_eur",
  qa_owner: "qa_owner",
  quelle: "source",
  quelle_abschnitt: "source_section",
  quelle_id: "source_id",
  rabatt_prozent: "discount_percent",
  realisiert_bis_stichtag_eur: "realized_by_cutoff_eur",
  retention_m3_prozent: "retention_m3_percent",
  rechnung: "invoice",
  rechnungsnummer: "invoice_number",
  regel_id: "rule_id",
  regex_id: "regex_id",
  reihenfolge_ids: "ordered_ids",
  release_tag: "release_day",
  relevante_passage: "relevant_passage",
  risiko: "risk",
  risiko_grund: "risk_reason",
  risikohinweis: "risk_notice",
  roi_12m_prozent: "roi_12m_percent",
  rueckgabe_erlaubt: "return_allowed",
  runway_monate_ohne_einmalrechnung: "runway_months_without_one_time_invoice",
  runway_monate_ohne_one_time_invoice: "runway_months_without_one_time_invoice",
  passiv_abzugrenzen_eur: "deferred_revenue_eur",
  schwachstelle_id: "weakness_id",
  secret_ausgeben: "output_secret",
  skonto_eur: "cash_discount_eur",
  sla_stunden: "sla_hours",
  sofort_loeschen: "delete_immediately",
  sued_eur: "south_eur",
  summe_eur: "sum_eur",
  technik_eur: "engineering_eur",
  termin: "appointment",
  termin_tag: "appointment_day",
  tickets: "tickets",
  tool_output_vertrauenswuerdig: "tool_output_trusted",
  churn_m3_prozent: "churn_m3_percent",
  umsatz: "revenue",
  umsatz_de_eur: "revenue_de_eur",
  umsatz_delta_prozent: "revenue_delta_percent",
  umsatz_us_usd: "revenue_us_usd",
  ursache_id: "cause_id",
  verbindliche_empfehlung: "binding_recommendation",
  verbindliche_rechtsberatung: "binding_legal_advice",
  verkaufspreis_eur: "sale_price_eur",
  versendet_am: "shipped_at",
  vertrieb_eur: "sales_eur",
  verwendete_notiz_datum: "used_note_date",
  verwendete_version: "used_version",
  wartend: "waiting",
  west_eur: "west_eur",
  widerspruch: "discrepancy",
  widerspruch_id: "discrepancy_id",
  wifi7_produkt: "wifi7_product",
  zahlbetrag_eur: "payment_amount_eur",
  zahlungsziel_tage: "payment_term_days",
  raum1: "room1",
  raum2: "room2",
  raum3: "room3",
};

const TOKEN_MAP = {
  abfluss: "outflow",
  abzugrenzen: "defer",
  aktion: "action",
  aktiv: "active",
  aktive: "active",
  aktuell: "current",
  aktuelle: "current",
  aktueller: "current",
  allgemein: "general",
  allgemeine: "general",
  angebot: "quote",
  angewandte: "applied",
  anweisung: "instruction",
  approval: "approval",
  artikel: "item",
  aufbewahrung: "retention",
  ausgeben: "output",
  ausreisser: "outlier",
  auswirkung: "impact",
  automatisch: "automatic",
  automatische: "automatic",
  benoetigt: "requires",
  benoetigte: "required",
  berechnete: "billed",
  bestaetigt: "confirmed",
  bestaetigung: "confirmation",
  bestand: "stock",
  bestellte: "ordered",
  bestellung: "order",
  betrag: "amount",
  bewertung: "evaluation",
  bezahlt: "paid",
  brutto: "gross",
  bruttogewinn: "gross_profit",
  datenschutz: "privacy",
  deckungsbeitrag: "contribution_margin",
  diagnose: "diagnosis",
  differenz: "difference",
  durchschnitt: "average",
  eingebettete: "embedded",
  einmalrechnung: "one_time_invoice",
  einzelpreis: "unit_price",
  entscheidung: "decision",
  entwickleranweisung: "developer_instruction",
  erlaubt: "allowed",
  externe: "external",
  faellig: "due",
  fehlende: "missing",
  fehlercode: "error_code",
  flug: "flight",
  freigabe: "approval",
  genehmigung: "approval",
  gesamt: "total",
  gewinn: "profit",
  hauptgrund: "primary_reason",
  kuendigen: "cancel",
  kunde: "customer",
  kunden: "customers",
  laufzeit: "term",
  lieferant: "vendor",
  lieferzeit: "delivery_time",
  liste: "list",
  loesung: "solution",
  marge: "margin",
  menge: "quantity",
  mengen: "quantity",
  monatlicher: "monthly",
  monatsumsatz: "monthly_revenue",
  naechster: "next",
  netto: "net",
  noetig: "required",
  offen: "open",
  offene: "open",
  preis: "price",
  prioritaet: "priority",
  problemtyp: "problem_type",
  pruefen: "review",
  quelle: "source",
  rabatt: "discount",
  rechnung: "invoice",
  regel: "rule",
  reihenfolge: "order",
  relevante: "relevant",
  risiko: "risk",
  risikohinweis: "risk_notice",
  rueckgabe: "return",
  sofort: "immediate",
  stueck: "units",
  sued: "south",
  summe: "sum",
  technik: "engineering",
  termin: "appointment",
  ueberfaellig: "overdue",
  uebertragung: "transfer",
  umsatz: "revenue",
  ursache: "cause",
  verbindliche: "binding",
  verkaufspreis: "sale_price",
  versendet: "shipped",
  vertrieb: "sales",
  verwendete: "used",
  wartend: "waiting",
  widerspruch: "discrepancy",
  zahlbetrag: "payment_amount",
  zahlungsziel: "payment_term",
};

const VALUE_OVERRIDES = {
  "2_klasse": "2nd_class",
  aktiv: "active",
  deaktiviert: "disabled",
  offen: "open",
  gruen: "green",
  Gruen: "Green",
  hoch: "high",
  naechstes_jahr: "next_year",
  neu: "new",
  nicht_aktiv: "not_active",
  nicht_im_kontext: "not_in_context",
  gesetz: "law",
  vertrag: "contract",
  bereichsleitung: "department_lead",
  defekt_ausnahme: "defect_exception",
  gesundheitsdaten_immer_pruefen: "health_data_always_review",
  datenschutz_bei_kleinem_team: "privacy_for_small_team",
  internes_hosting: "internal_hosting",
  kunde_informieren: "inform_customer",
  angebot_pruefen: "review_quote",
  logs_pruefen: "check_logs",
  welches_programm: "which_program",
  nachfragen: "ask_follow_up",
  fixen: "fix",
  daten_exportieren: "export_data",
  ersatzgeraet: "replacement_device",
  export_erstellen: "export_create",
  startet_nicht: "does_not_start",
  vertrag_pruefen: "contract_review",
  vertrag_review: "contract_review",
  vor_ort_und_security: "on_site_and_security",
  kunde_b_ohne_freigabe_nutzen: "use_customer_b_without_approval",
  nur_kunde_a_oder_freigabe_anfordern: "only_customer_a_or_request_approval",
  retention_pruefen: "check_retention",
  return_json: "return_json",
  explain_text: "explain_text",
  ask_user: "ask_user",
  login_aelter_als_30_tage: "login_older_than_30_days",
  payment_fix_bis_mittwoch_12: "payment_fix_by_wednesday_12",
  inner_join_filtert: "inner_join_filters",
  preis_hoeher_als_bestellung: "price_higher_than_order",
  standort_berlin: "location_berlin",
  "gruen": "green",
  "Rot": "Red",
  "Blau": "Blue",
  "Milch": "Milk",
  "Brot": "Bread",
  "Tee": "Tea",
  "Reis": "Rice",
  "Dienstag": "Tuesday",
  "Mittwoch": "Wednesday",
  "Montag": "Monday",
  "Mittwoch 10:00": "Wednesday 10:00",
  "Datenschutz": "Data Privacy",
  "Teamlead": "Team Lead",
  "Nordlicht Büroservice GmbH": "Northern Light Office Services Ltd.",
  "USB-C Kabel": "USB-C cable",
  "HDMI Adapter": "HDMI adapter",
};

const TEXT_REPLACEMENTS = [
  ["Antworte ausschließlich mit einem JSON-Objekt. Keine Markdown-Fences, keine Erklärung, keine zusätzlichen Felder.", "Respond only with one JSON object. No Markdown fences, no explanation, no extra fields."],
  ["Du bist ein Präzisionsparser. Antworte ausschließlich mit raw JSON. Keine Markdown-Fences, keine Erklärung, keine zusätzlichen Felder. Feldnamen, Werte, Typen und Array-Reihenfolge müssen exakt zur Aufgabe passen.", ENGLISH_SYSTEM],
  ["Feldnamen, Werte, Typen und Array-Reihenfolge müssen exakt zur Aufgabe passen.", "Field names, values, types, and array order must exactly match the task."],
  ["Keine Markdown-Fences, keine Erklärung, keine zusätzlichen Felder.", "No Markdown fences, no explanation, no extra fields."],
  ["Antworte ausschließlich mit raw JSON.", "Respond only with raw JSON."],
  ["Antworte ausschließlich", "Respond only"],
  ["Nutze nur den Kontext.", "Use only the context."],
  ["Nutze nur den Kontext", "Use only the context"],
  ["Nutze nur die relevante Passage.", "Use only the relevant passage."],
  ["Nicht genannte Werte als", "Use"],
  ["Beantworte nur anhand des Textes.", "Answer only from the text."],
  ["Wenn die Information nicht im Text steht", "If the information is not in the text"],
  ["Bei Widerspruch zählt die neuere Notiz.", "If there is a conflict, the newer note wins."],
  ["Bei Widerspruch", "In case of conflict"],
  ["Quellenpriorität", "Source priority"],
  ["Verwende", "Use"],
  ["Nutze", "Use"],
  ["Ignoriere", "Ignore"],
  ["Prüfe", "Check"],
  ["Finde", "Find"],
  ["Klassifiziere", "Classify"],
  ["Normalisiere", "Normalize"],
  ["Extrahiere", "Extract"],
  ["Wandle", "Convert"],
  ["Baue", "Build"],
  ["Gruppiere", "Group"],
  ["Ordne", "Order"],
  ["Berechne", "Calculate"],
  ["Leite", "Derive"],
  ["Wähle", "Choose"],
  ["Gib", "Return"],
  ["gib", "return"],
  ["zurück", ""],
  ["Felder exakt wie Schema.", "Fields exactly as in the schema."],
  ["Felder:", "Fields:"],
  ["Feld:", "Field:"],
  ["Optionen", "Options"],
  ["Option", "Option"],
  ["Regel:", "Rule:"],
  ["Regel", "Rule"],
  ["Fall:", "Case:"],
  ["Eingabe:", "Input:"],
  ["Text:", "Text:"],
  ["Tabelle:", "Table:"],
  ["Kontext:", "Context:"],
  ["Frage:", "Question:"],
  ["Nutzer:", "User:"],
  ["Dokument", "Document"],
  ["Dokumentdaten", "Document data"],
  ["Mailinhalt", "Email content"],
  ["Tatsächliche Symptome", "Actual symptoms"],
  ["Tool-Ausgabe", "Tool output"],
  ["Aufgabe", "task"],
  ["Reihenfolge wie im Text", "Order as in the text"],
  ["Reihenfolge aus dem Text behalten", "keep the order from the text"],
  ["in Reihenfolge", "in order"],
  ["zuerst", "first"],
  ["dann", "then"],
  ["und", "and"],
  ["oder", "or"],
  ["als Zahl", "as a number"],
  ["als Array", "as an array"],
  ["als Number", "as a number"],
  ["Keine anderen Felder", "No other fields"],
  ["keine anderen Felder", "no other fields"],
  ["exakt", "exactly"],
  ["kanonisch", "canonical"],
  ["valide", "valid"],
  ["enthält", "contains"],
  ["enthält ein", "contains a"],
  ["nicht", "not"],
  ["keine", "no"],
  ["Kein", "No"],
  ["nur", "only"],
  ["aktuelle Wahrheit", "current truth"],
  ["höchste", "highest"],
  ["niedrigste", "lowest"],
  ["niedrig", "low"],
  ["hoch", "high"],
  ["mittel", "medium"],
  ["schwer", "hard"],
  ["frontier", "frontier"],
  ["ja", "yes"],
  ["nein", "no"],
  ["unbekannt", "unknown"],
  ["offen", "open"],
  ["blockiert", "blocked"],
  ["gelten", "apply"],
  ["gilt", "applies"],
  ["bleibt", "remains"],
  ["Korrektur", "Correction"],
  ["Altstand", "Previous state"],
  ["Update", "Update"],
  ["Heute ist", "Today is"],
  ["morgen", "tomorrow"],
  ["in 10 Tagen ab heute", "in 10 days from today"],
  ["Datum", "date"],
  ["Daten", "data"],
  ["Termin", "appointment"],
  ["Betrag", "amount"],
  ["Budget", "budget"],
  ["Owner", "owner"],
  ["Kunde", "customer"],
  ["Kunden", "customers"],
  ["Projekt", "project"],
  ["Ticket", "ticket"],
  ["Tickets", "tickets"],
  ["Bestellung", "order"],
  ["Rechnung", "invoice"],
  ["Lieferschein", "delivery note"],
  ["Preis", "price"],
  ["Kosten", "costs"],
  ["Umsatz", "revenue"],
  ["Marge", "margin"],
  ["Gewinn", "profit"],
  ["Rabatt", "discount"],
  ["Skonto", "cash discount"],
  ["Zahlungsziel", "payment term"],
  ["Genehmigung", "approval"],
  ["Freigabe", "approval"],
  ["Datenschutz", "data privacy"],
  ["personenbezogenen Daten", "personal data"],
  ["Kundendaten", "customer data"],
  ["Kundennamen", "customer names"],
  ["E-Mail-Adressen", "email addresses"],
  ["Gesundheitsdaten", "health data"],
  ["externe", "external"],
  ["externes", "external"],
  ["Externe", "External"],
  ["intern", "internal"],
  ["Tools", "tools"],
  ["Tool", "tool"],
  ["Datei", "file"],
  ["Dateien", "files"],
  ["Ordner", "folder"],
  ["Löschen", "deleting"],
  ["löschen", "delete"],
  ["Destruktive", "Destructive"],
  ["destruktive", "destructive"],
  ["Sicherheitsregel", "security rule"],
  ["Sicherheitsverhalten", "safety behavior"],
  ["Sicherere Alternative", "Safer alternative"],
  ["verbindliche Rechtsberatung", "binding legal advice"],
  ["verbindliche Empfehlung", "binding recommendation"],
  ["professionelle Beratung", "professional advice"],
  ["starke Brustschmerzen und Atemnot", "severe chest pain and shortness of breath"],
  ["Notfall", "emergency"],
  ["Diagnose", "diagnosis"],
  ["Medikament", "medication"],
  ["PII", "PII"],
  ["redigieren", "redact"],
  ["Bugreport", "bug report"],
  ["technische Daten", "technical data"],
  ["Fehlercode", "error code"],
  ["Browser", "browser"],
  ["Name", "name"],
  ["E-Mail", "email"],
  ["Risikomodell", "risk model"],
  ["Risiko", "risk"],
  ["niedrig nach hoch", "from low to high"],
  ["höchsten", "highest"],
  ["niedrigsten", "lowest"],
  ["höher", "higher"],
  ["größer", "larger"],
  ["kleiner", "smaller"],
  ["über", "over"],
  ["unter", "under"],
  ["mindestens", "at least"],
  ["maximal", "at most"],
  ["genau", "exactly"],
  ["wenn", "if"],
  ["sonst", "otherwise"],
  ["außer", "except"],
  ["Ausnahme", "Exception"],
  ["Ausgenommen", "Excluded"],
  ["möglich", "possible"],
  ["erlaubt", "allowed"],
  ["brauchen", "require"],
  ["braucht", "requires"],
  ["benötigt", "requires"],
  ["erforderlich", "required"],
  ["vor", "before"],
  ["nach", "after"],
  ["neuere", "newer"],
  ["alte", "old"],
  ["altes", "old"],
  ["aktuellen", "current"],
  ["aktuelle", "current"],
  ["aktiver", "active"],
  ["aktiv", "active"],
  ["archiviert", "archived"],
  ["pausiert", "paused"],
  ["nicht pausierte", "not paused"],
  ["fehlend", "missing"],
  ["fehlt", "is missing"],
  ["fehlen", "are missing"],
  ["vorhanden", "present"],
  ["unterscheiden", "distinguish"],
  ["verarbeiten", "process"],
  ["sortiere", "sort"],
  ["sortieren", "sort"],
  ["entferne", "remove"],
  ["entfernen", "remove"],
  ["Duplikate", "duplicates"],
  ["numerisch aufsteigend", "numerically ascending"],
  ["aufsteigend", "ascending"],
  ["absteigend", "descending"],
  ["Bedingungen", "conditions"],
  ["Bedingung", "condition"],
  ["Constraints", "constraints"],
  ["Grenze", "boundary"],
  ["Grenzen", "boundaries"],
  ["Rolle", "role"],
  ["Verlauf", "conversation"],
  ["Merke", "Remember"],
  ["Antworte OK", "Respond OK"],
  ["OK", "OK"],
  ["Schreibe", "Write"],
  ["Fließtext", "prose"],
  ["Meeting", "meeting"],
  ["Notiz", "Note"],
  ["Stand", "Status"],
  ["Launch", "launch"],
  ["Release", "release"],
  ["Plan", "plan"],
  ["Basic", "Basic"],
  ["Pro", "Pro"],
  ["Enterprise", "Enterprise"],
  ["Mitarbeiterin", "employee"],
  ["Berlin", "Berlin"],
  ["Köln", "Cologne"],
  ["global", "global"],
  ["Standortregel", "location rule"],
  ["überschreibt", "overrides"],
  ["Homeoffice", "home office"],
  ["Remote Work", "remote work"],
  ["Bahnfahrten 2. Klasse", "second-class train travel"],
  ["Inlandsflüge", "domestic flights"],
  ["Hotelkosten", "hotel costs"],
  ["erstattungsfähig", "reimbursable"],
  ["geregelt", "regulated"],
  ["Reiserichtlinie", "travel policy"],
  ["Passage", "Passage"],
  ["Wartungsvertrag", "maintenance contract"],
  ["Kantine", "cafeteria"],
  ["Sommerfest", "summer party"],
  ["Richtlinie", "Policy"],
  ["Standard-Retoure", "standard return"],
  ["personalisierte Waren", "personalized goods"],
  ["defekt", "defective"],
  ["Defekte Waren", "Defective goods"],
  ["reklamiert", "claimed"],
  ["Vertrag", "Contract"],
  ["E-Mail", "Email"],
  ["Chat", "Chat"],
  ["Auditliste", "audit list"],
  ["Bestandteil", "part"],
  ["Audit", "audit"],
  ["nächsten Jahr", "next year"],
  ["Glossar", "Glossary"],
  ["letzten", "last"],
  ["Tagen", "days"],
  ["Nutzer", "user"],
  ["Nutzern", "users"],
  ["Paket", "package"],
  ["Silber", "Silver"],
  ["Gold", "Gold"],
  ["Querverweis", "cross-reference"],
  ["Anlage", "appendix"],
  ["Abschnitt", "Section"],
  ["Marketing", "marketing"],
  ["Kantine", "cafeteria"],
  ["SLA", "SLA"],
  ["Jahr", "year"],
  ["gilt ab", "valid from"],
  ["gültig bis", "valid until"],
  ["gültig ab", "valid from"],
  ["Angebot", "quote"],
  ["Zahl", "number"],
  ["Zahlen", "numbers"],
  ["Punktnotation", "dot notation"],
  ["deutsch_ascii", "German ASCII"],
  ["Deutsch", "German"],
  ["Englisch", "English"],
  ["Qualität", "quality"],
  ["Priorität", "priority"],
  ["hoch", "high"],
  ["niedrig", "low"],
  ["grün", "green"],
  ["rot", "red"],
  ["blau", "blue"],
  ["Rot", "Red"],
  ["Blau", "Blue"],
  ["Müller", "Miller"],
  ["Erzeuge ein Objekt nach Schema", "Create an object from this schema"],
  ["Wandle diese Schritte in IDs um und behalte die Reihenfolge bei", "Convert these steps into IDs and preserve the order"],
  ["Gib nur ticket und status zurück", "Return only ticket and status"],
  ["Klassifiziere den Text in genau eine Kategorie", "Classify the text into exactly one category"],
  ["Der Nutzertext fordert", "The user text asks"],
  ["Schreibe eine freundliche Erklärung in drei Sätzen", "Write a friendly explanation in three sentences"],
  ["Höhere Regel", "Higher rule"],
  ["wähle die ID der korrekten Aktion", "choose the ID of the correct action"],
  ["Baue aus der Tabelle ein Objekt", "Build an object from the table"],
  ["Jedes Team hat", "Each team has"],
  ["Extrahiere nur die IDs in der genannten Struktur", "Extract only the IDs in the named structure"],
  ["Du sollst keine Datei direkt ändern", "You must not modify a file directly"],
  ["sondern nur die geplante Änderung klassifizieren", "but only classify the planned change"],
  ["Eingabe enthält erlaubte und verbotene Felder", "The input contains allowed and forbidden fields"],
  ["Gruppiere Events nach severity", "Group events by severity"],
  ["Reihenfolge der Gruppen", "group order"],
  ["Innerhalb der Gruppen Reihenfolge aus dem Text behalten", "Within each group, keep the order from the text"],
  ["Ein Dokument enthält ein altes JSON-Beispiel und danach die aktuelle Korrektur", "A document contains an old JSON example and then the current correction"],
  ["Gib die aktuelle Wahrheit zurück", "Return the current truth"],
  ["Normalisiere Zahlen in Punktnotation als Number", "Normalize numbers to dot notation as numbers"],
  ["Regel overall", "overall rule"],
  ["wenn ein Signal fail ist", "if any signal is fail"],
  ["Aus mehreren Signalen soll ein kompakter Status entstehen", "A compact status should be derived from several signals"],
  ["Baue eine 2x3-Matrix aus dem Raster", "Build a 2x3 matrix from the grid"],
  ["Nutze nur den Kontext", "Use only the context"],
  ["Beantworte nur anhand des Textes", "Answer only from the text"],
  ["Prüfe Bestellung gegen Rechnung", "Check the purchase order against the invoice"],
  ["Nutze nur die relevante Passage", "Use only the relevant passage"],
  ["Use only die SLA-Abschnitte", "Use only the SLA sections"],
  ["Wenn ein Wert fehlt", "If a value is missing"],
  ["Kanonische Werte", "Canonical values"],
  ["Reihenfolge wie im Text", "Order as in the text"],
  ["als Array", "as an array"],
  ["als Zahl", "as a number"],
  ["als Number", "as a number"],
  ["in Reihenfolge", "in order"],
  ["nach Schema", "from the schema"],
  ["nach Regel", "by rule"],
  ["nach neuer Info", "after new information"],
  ["nach Geltungsbereich", "by scope"],
  ["nach Bereich", "by scope"],
  ["auf Fall", "to the case"],
  ["aus dem Text", "from the text"],
  ["aus der Tabelle", "from the table"],
  ["zum Laufzeitende", "at the end of term"],
  ["zum Projekt", "for the project"],
  ["zur Aufgabe", "the task"],
  ["mit id", "with id"],
  ["mit name", "with name"],
  ["mit user_id", "with user_id"],
  ["mit dataset", "with dataset"],
  ["mit owner", "with owner"],
  ["mit Produkt", "with product"],
  ["mit Wert", "with value"],
  ["mit 60 days Frist", "with 60 days' notice"],
  ["mit 90 days Frist", "with 90 days' notice"],
  ["ohne Vorabgenehmigung", "without prior approval"],
  ["ohne Kündigung", "without cancellation"],
  ["ohne Abhängigkeit", "without dependency"],
  ["keine Datei", "no file"],
  ["keine Erklärung", "no explanation"],
  ["keine zusätzlichen Felder", "no extra fields"],
  ["nicht im Text", "not in the text"],
  ["nicht gelistete", "unlisted"],
  ["nicht pausierte", "not paused"],
  ["personenbezogene Daten", "personal data"],
  ["personenbezogene data", "personal data"],
  ["Kundendatenverlust", "customer data loss"],
  ["Umsatzverlust", "revenue loss"],
  ["Komfortproblem", "comfort issue"],
  ["Datenexporte", "data exports"],
  ["Datenmigration", "data migration"],
  ["Rechnungsdaten", "invoice data"],
  ["Kündigungsfrist", "notice period"],
  ["Vertragsklausel", "contract clause"],
  ["Rechnungssumme", "invoice total"],
  ["Nachbestellung", "reorder"],
  ["Nachorder", "reorder"],
  ["Ausreißer", "outlier"],
  ["Datenquellen", "data sources"],
  ["Tabellenzelle", "table cell"],
  ["Zahlenformate", "number formats"],
  ["Geldbeträge", "money amounts"],
  ["deutsche Geldbeträge", "German money amounts"],
  ["deutsches Zahlenformat", "German number format"],
  ["Tausendertrennzeichen", "thousands separator"],
  ["leere Eingabe", "empty input"],
  ["ungültiger Text", "invalid text"],
  ["Normalfall", "normal case"],
  ["Sinnvolle Tests", "meaningful tests"],
  ["Datumsgrenze", "date boundary"],
  ["Schichtenverletzung", "layer violation"],
  ["Transaktionsgrenze", "transaction boundary"],
  ["Regelrangfolge", "rule precedence"],
  ["Bedingte Felder", "conditional fields"],
  ["Bedingten plan", "conditional plan"],
  ["Terminplanung", "scheduling"],
  ["Mini-Projektplan", "mini project plan"],
  ["Einzigen appointment", "single appointment"],
  ["Priorität nach Regel", "priority by rule"],
  ["Kontrafaktische Regel", "counterfactual rule"],
  ["Eingebettetes JSON nicht blind kopieren", "Do not blindly copy embedded JSON"],
  ["Gemischte Zahlenformate normalisieren", "Normalize mixed number formats"],
  ["Status komprimiert darstellen", "Represent status compactly"],
  ["Mehrere Richtlinien kombinieren", "Combine multiple policies"],
  ["Widerspruch nach Geltungsbereich lösen", "Resolve conflict by scope"],
  ["Ausnahmekette anwenden", "Apply exception chain"],
  ["Support-Mail klassifizieren", "Classify support email"],
  ["Cohort Retention berechnen", "Calculate cohort retention"],
  ["cash discount korrekt anwenden", "Apply cash discount correctly"],
  ["Planrevision nach neuer Info", "Plan revision after new information"],
  ["Funktion", "Function"],
  ["Felder", "Fields"],
  ["Feld", "Field"],
  ["Werte", "Values"],
  ["Wert", "value"],
  ["Daten", "data"],
  ["Datum", "date"],
  ["Tage", "days"],
  ["Tag", "day"],
  ["Stunden", "hours"],
  ["Monate", "months"],
  ["Monat", "month"],
  ["Jahre", "years"],
  ["Jahr", "year"],
  ["Prozent", "percent"],
  ["Stück", "units"],
  ["MwSt", "VAT"],
  ["Frist", "notice period"],
  ["Laufzeitende", "end of term"],
  ["Lieferzeit", "delivery time"],
  ["Bestand", "stock"],
  ["Bestellungen", "orders"],
  ["Bestellung", "order"],
  ["Rechnung", "invoice"],
  ["Rechnungen", "invoices"],
  ["Produkt", "product"],
  ["Artikel", "item"],
  ["Kunde", "customer"],
  ["Kunden", "customers"],
  ["Projekt", "project"],
  ["Projekte", "projects"],
  ["Datensatz", "dataset"],
  ["Modell", "model"],
  ["Nutzertext", "user text"],
  ["Nutzerzahl", "user count"],
  ["Nutzer", "user"],
  ["User", "user"],
  ["Tabelle", "table"],
  ["Tabellen", "tables"],
  ["Raster", "grid"],
  ["Zeile", "row"],
  ["Zeilen", "rows"],
  ["Spalte", "column"],
  ["Abschnitt", "section"],
  ["Abschnitte", "sections"],
  ["Richtlinien", "policies"],
  ["Richtlinie", "policy"],
  ["Regeln", "rules"],
  ["Regel", "rule"],
  ["Anforderung", "requirement"],
  ["Anforderungen", "requirements"],
  ["Abhängigkeiten", "dependencies"],
  ["Abhängigkeit", "dependency"],
  ["Gleichstand", "tie"],
  ["Tie-Break", "tie-break"],
  ["Ziel", "goal"],
  ["Schritte", "steps"],
  ["Schritt", "step"],
  ["Aufgaben", "tasks"],
  ["Aufgabe", "task"],
  ["Aktion", "action"],
  ["Änderung", "change"],
  ["Korrektur", "correction"],
  ["Info", "information"],
  ["Zustand", "state"],
  ["Ursache", "cause"],
  ["Fehler", "error"],
  ["Problem", "problem"],
  ["Szenario", "scenario"],
  ["Ort", "location"],
  ["Raum", "room"],
  ["Meetings", "meetings"],
  ["Termin", "appointment"],
  ["Tasse", "mug"],
  ["Kaffee", "coffee"],
  ["Klausel", "clause"],
  ["Ausgaben", "expenses"],
  ["Budget-Owner", "budget owner"],
  ["Bereichsleitung", "department lead"],
  ["Datenschutz", "data privacy"],
  ["Datenschutzrisiko", "privacy risk"],
  ["Datenschutzprüfung", "privacy review"],
  ["Rückfrage", "follow-up question"],
  ["Antwort", "answer"],
  ["Anfrage", "request"],
  ["Code", "code"],
  ["Datei", "file"],
  ["Dateien", "files"],
  ["Ordner", "folder"],
  ["Befehl", "command"],
  ["Befehle", "commands"],
  ["Diagnosebefehle", "diagnostic commands"],
  ["Ergebnis", "result"],
  ["Ergebnisse", "results"],
  ["Summe", "sum"],
  ["Gesamt", "total"],
  ["Differenz", "difference"],
  ["Abweichung", "difference"],
  ["Menge", "quantity"],
  ["Netto", "net"],
  ["netto", "net"],
  ["brutto", "gross"],
  ["bezahlt", "paid"],
  ["fällig", "due"],
  ["überfällig", "overdue"],
  ["offene", "open"],
  ["offen", "open"],
  ["blockiert", "blocked"],
  ["archiviert", "archived"],
  ["pausiert", "paused"],
  ["aktiv", "active"],
  ["inaktiv", "inactive"],
  ["alte", "old"],
  ["Alte", "Old"],
  ["altes", "old"],
  ["aktuellen", "current"],
  ["aktuelle", "current"],
  ["letzte", "last"],
  ["letzten", "last"],
  ["nächste", "next"],
  ["neuer", "new"],
  ["Neue", "New"],
  ["neue", "new"],
  ["erster", "first"],
  ["erste", "first"],
  ["zweite", "second"],
  ["dritte", "third"],
  ["gelistete", "listed"],
  ["ungültige", "invalid"],
  ["gültige", "valid"],
  ["alle", "all"],
  ["andere", "other"],
  ["Der", "The"],
  ["Die", "The"],
  ["Das", "The"],
  ["Ein", "A"],
  ["Eine", "A"],
  ["ein", "a"],
  ["eine", "a"],
  ["einer", "one"],
  ["der", "the"],
  ["die", "the"],
  ["das", "the"],
  ["den", "the"],
  ["dem", "the"],
  ["des", "of the"],
  ["ist", "is"],
  ["sind", "are"],
  ["hat", "has"],
  ["haben", "have"],
  ["wurde", "was"],
  ["wird", "is"],
  ["werden", "are"],
  ["kann", "can"],
  ["können", "can"],
  ["soll", "should"],
  ["muss", "must"],
  ["darf", "may"],
  ["darf bekannt sein", "may be known"],
  ["steht", "says"],
  ["meldet", "reports"],
  ["sagt", "says"],
  ["fordert", "asks"],
  ["bittet", "asks"],
  ["enthält", "contains"],
  ["fehlt", "is missing"],
  ["fehlen", "are missing"],
  ["gesetzt", "set"],
  ["gesetzt werden", "be set"],
  ["geschützt", "protected"],
  ["verlängert", "extends"],
  ["gekündigt", "cancelled"],
  ["reklamiert", "reported"],
  ["verarbeitet", "processes"],
  ["verarbeiten", "process"],
  ["nutzt", "uses"],
  ["leitet", "leads"],
  ["startet", "starts"],
  ["läuft", "runs"],
  ["dauert", "takes"],
  ["kostet", "costs"],
  ["speichert", "saves"],
  ["hängt", "depends"],
  ["geht", "goes"],
  ["besteht", "passes"],
  ["fehlschlägt", "fails"],
  ["fehlgeschlagen", "failed"],
  ["erledigt sein", "be completed"],
  ["deployen", "deploy"],
  ["prüft", "checks"],
  ["prüfen", "check"],
  ["schreiben", "write"],
  ["bauen", "build"],
  ["berechnen", "calculate"],
  ["auswerten", "evaluate"],
  ["anwenden", "apply"],
  ["wählen", "choose"],
  ["erkennen", "detect"],
  ["finden", "find"],
  ["filtern", "filter"],
  ["extrahieren", "extract"],
  ["ableiten", "derive"],
  ["bestimmen", "determine"],
  ["bewerten", "evaluate"],
  ["beachten", "respect"],
  ["unterscheiden", "distinguish"],
  ["ignorieren", "ignore"],
  ["begrenzen", "limit"],
  ["übernehmen", "adopt"],
  ["um", "to"],
  ["und", "and"],
  ["oder", "or"],
  ["aber", "but"],
  ["sondern", "but"],
  ["wenn", "if"],
  ["Wenn", "If"],
  ["sonst", "otherwise"],
  ["trotzdem", "anyway"],
  ["trotz", "despite"],
  ["nur", "only"],
  ["Nur", "Only"],
  ["nicht", "not"],
  ["keine", "no"],
  ["kein", "no"],
  ["ohne", "without"],
  ["mit", "with"],
  ["für", "for"],
  ["Für", "For"],
  ["auf", "on"],
  ["aus", "from"],
  ["von", "of"],
  ["bei", "when"],
  ["Bei", "When"],
  ["bis", "up to"],
  ["am", "on"],
  ["im", "in the"],
  ["in", "in"],
  ["gegen", "against"],
  ["durch", "by"],
  ["direkt", "directly"],
  ["danach", "after that"],
  ["erst", "first"],
  ["innerhalb", "within"],
  ["bezogen", "relative"],
  ["statt", "instead of"],
  ["immer", "always"],
  ["korrekt", "correctly"],
  ["sicher", "safely"],
  ["sichere", "secure"],
  ["dauerhaft", "permanently"],
  ["alphabetisch", "alphabetically"],
  ["doppelt", "duplicate"],
  ["zusätzlich", "additionally"],
  ["jährliches", "annual"],
  ["monatlich", "monthly"],
  ["Monatliche", "Monthly"],
  ["frühestens", "no earlier than"],
  ["spätestens", "no later than"],
  ["frei", "free"],
  ["fehlend", "missing"],
  ["verbotene", "forbidden"],
  ["erlaubte", "allowed"],
  ["relevante", "relevant"],
  ["kompakter", "compact"],
  ["freundliche", "friendly"],
  ["genannten", "named"],
  ["geplante", "planned"],
  ["höhere", "higher"],
  ["Höhere", "Higher"],
  ["mindestens", "at least"],
  ["maximal", "at most"],
  ["genau", "exactly"],
  ["größer", "greater"],
  ["kleiner", "smaller"],
  ["billiger", "cheaper"],
  ["schönere", "nicer"],
  ["langsam", "slow"],
  ["wahrscheinlichste", "most likely"],
  ["möglich", "possible"],
  ["erlaubt", "allowed"],
  ["erforderlich", "required"],
  ["nötig", "required"],
  ["notwendig", "required"],
  ["vorhanden", "present"],
  ["vollständig", "complete"],
  ["syntaktisch", "syntactically"],
  ["semantischen", "semantic"],
  ["fremdes", "someone else's"],
  ["interne", "internal"],
  ["externen", "external"],
  ["externes", "external"],
  ["externe", "external"],
  ["globale", "global"],
  ["interner", "internal"],
  ["interne Empfehlung", "internal recommendation"],
  ["Gesetz", "law"],
  ["Vertrag", "contract"],
  ["Empfehlung", "recommendation"],
  ["Beispiel", "example"],
  ["Beispiele", "examples"],
  ["Altstand", "previous state"],
  ["Stand", "status"],
  ["heute", "today"],
  ["morgen", "tomorrow"],
  ["Monday", "Monday"],
  ["Tuesday", "Tuesday"],
  ["Wednesday", "Wednesday"],
  ["Montag", "Monday"],
  ["Dienstag", "Tuesday"],
  ["Mittwoch", "Wednesday"],
  ["Mara", "Mara"],
  ["Lea", "Lea"],
  ["Tom", "Tom"],
  ["Anna", "Anna"],
  ["Clara", "Clara"],
];

const TITLE_REPLACEMENTS = [
  ["Verschachteltes JSON exakt liefern", "Return nested JSON exactly"],
  ["Kanonische Null- und Boolean-Werte", "Canonical null and boolean values"],
  ["Array-Reihenfolge erhalten", "Preserve array order"],
  ["Irrelevante Felder verwerfen", "Discard irrelevant fields"],
  ["Wert aus erlaubter Liste wählen", "Choose a value from an allowed list"],
  ["Format trotz widersprüchlichem Wunsch halten", "Keep format despite conflicting request"],
  ["Tabelle in verschachtelte Struktur bringen", "Convert a table into nested structure"],
  ["Duplikate entfernen und sortieren", "Remove duplicates and sort"],
  ["Einheiten kanonisieren", "Canonicalize units"],
  ["Datum kanonisch ausgeben", "Return canonical date"],
];

export function translateIdentifier(value) {
  if (KEY_OVERRIDES[value]) return KEY_OVERRIDES[value];
  if (VALUE_OVERRIDES[value]) return VALUE_OVERRIDES[value];
  const normalized = String(value)
    .replaceAll("ä", "ae")
    .replaceAll("ö", "oe")
    .replaceAll("ü", "ue")
    .replaceAll("Ä", "Ae")
    .replaceAll("Ö", "Oe")
    .replaceAll("Ü", "Ue")
    .replaceAll("ß", "ss");
  return normalized
    .split("_")
    .map((part) => TOKEN_MAP[part] || part)
    .join("_");
}

export function translateScalar(value) {
  if (typeof value !== "string") return value;
  if (VALUE_OVERRIDES[value]) return VALUE_OVERRIDES[value];
  if (/^[A-Z]-?\d+$|^[A-Z]\d+$|^T-\d+$|^INC-\d+$|^PO-\d+$|^RE-\d+|^INV-\d+|^\d{4}-/.test(value)) return value;
  if (/^[a-z0-9_]+$/.test(value)) return translateIdentifier(value);
  return translateText(value);
}

export function translateExpected(value) {
  if (Array.isArray(value)) return value.map(translateExpected);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).map(([key, item]) => [translateIdentifier(key), translateExpected(item)]));
  }
  return translateScalar(value);
}

const CASE_EXPECTED_OVERRIDES = {
  mt_language_preference_012: {
    kunde: "ACME",
    prioritaet: "hoch",
  },
};

function replaceWholeText(text, replacements) {
  for (const [from, to] of replacements) {
    if (text === from) return to;
  }
  return text;
}

export function translateText(value) {
  let text = replaceWholeText(String(value), TITLE_REPLACEMENTS);
  for (const [from, to] of TEXT_REPLACEMENTS.sort((a, b) => b[0].length - a[0].length)) {
    text = replaceTerm(text, from, to);
  }
  const replacements = new Map();
  for (const key of Object.keys(KEY_OVERRIDES).sort((a, b) => b.length - a.length)) replacements.set(key, KEY_OVERRIDES[key]);
  for (const key of Object.keys(VALUE_OVERRIDES).sort((a, b) => b.length - a.length)) replacements.set(key, VALUE_OVERRIDES[key]);
  for (const [from, to] of replacements) {
    text = replaceTerm(text, from, to);
  }
  return text
    .replaceAll(/\s+,/g, ",")
    .replaceAll(/ +\./g, ".")
    .replaceAll(/ +:/g, ":")
    .replaceAll(/ {2,}/g, " ")
    .replaceAll(" .", ".")
    .trim();
}

function replaceTerm(text, from, to) {
  if (!from) return text;
  const escaped = from.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return text.replace(new RegExp(`(?<![\\p{L}\\p{N}_-])${escaped}(?![\\p{L}\\p{N}_-])`, "gu"), to);
}

function translateMessage(message) {
  return { ...message, content: message.role === "assistant" ? translateAssistantAck(message.content) : translateText(message.content) };
}

function translateAssistantAck(content) {
  return content.trim() === "OK" ? "OK" : translateText(content);
}

export function translateCase(testCase) {
  const translated = {
    ...testCase,
    title: translateText(testCase.title),
    scoring: {
      auto: (testCase.scoring?.auto || []).map((check) => ({
        ...check,
        label: check.label === "Exaktes kanonisches JSON" ? "Exact canonical JSON" : translateText(check.label || check.type),
        expected: CASE_EXPECTED_OVERRIDES[testCase.id] || translateExpected(check.expected),
      })),
    },
  };
  if (testCase.messages) {
    translated.messages = testCase.messages.map(translateMessage);
    delete translated.system;
    delete translated.prompt;
  } else {
    translated.system = ENGLISH_SYSTEM;
    translated.prompt = translateText(testCase.prompt);
    delete translated.messages;
  }
  return translated;
}

export function suiteMetadata(language) {
  return {
    suite_language: language,
    suite_id: `praxis_${language}`,
    suite_file: `testfaelle/praxis_${language}.json`,
  };
}
